# More data and merged dos lables - same features as in the original article

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
Friday_data = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
Wednesday_data = "Wednesday-workingHours.pcap_ISCX.csv"
# Read the existing DataFrame from the first CSV file
df1 = pd.read_csv(Friday_data, sep=',')

# Read the new data from the second CSV file
df2 = pd.read_csv(Wednesday_data, sep=',')

# Append the new data to the end of the existing DataFrame
merged_df = pd.concat([df1, df2], ignore_index=True)


In [13]:
merged_df.shape

(918448, 79)

In [15]:
merged_df.isnull().any().any() # check if we have nan values.

True

In [16]:
#PREPROCCSING
# Replace infinite or very large values with NaN
merged_df.replace([np.inf, -np.inf], np.nan, inplace=True)

#drop any instance that is missing a feture
merged_df = merged_df.dropna()
merged_df.isnull().any().any() # check if we have nan values.

False

In [17]:
merged_df[' Label'].unique()

array(['BENIGN', 'DDoS'], dtype=object)

In [18]:
merged_df.shape

(917117, 79)

In [8]:
non_benign_df = merged_df[merged_df[' Label'] != 'BENIGN']
benign_df = merged_df[merged_df[' Label'] == 'BENIGN']

In [20]:
print(non_benign_df.shape)
print(benign_df.shape)

(379748, 79)
(537369, 79)


In [19]:
non_benign_df.head(10)

(379748, 79)


Destination Port   Flow Duration   Total Fwd Packets  \
18883                 80         1293792                   3   
18884                 80         4421382                   4   
18885                 80         1083538                   3   
18886                 80        80034360                   8   
18887                 80          642654                   3   
18888                 80        79731718                   8   
18889                 80          306157                   3   
18890                 80        79780371                   8   
18891                 80          682575                   3   
18892                 80        79098660                   8   

        Total Backward Packets  Total Length of Fwd Packets  \
18883                        7                           26   
18884                        0                           24   
18885                        6                           26   
18886                        4                           56   
18887                        6                           26   
18888                        5                           56   
18889                        6                           26   
18890                        4                           56   
18891                        5                           26   
18892                        6                           56   

        Total Length of Bwd Packets   Fwd Packet Length Max  \
18883                         11607                      20   
18884                             0                       6   
18885                         11601                      20   
18886                         11601                      20   
18887                         11607                      20   
18888                         11601                      20   
18889                         11607                      20   
18890                         11607                      20   
18891                         11607                      20   
18892                         11607                      20   

        Fwd Packet Length Min   Fwd Packet Length Mean  \
18883                       0                 8.666667   
18884                       6                 6.000000   
18885                       0                 8.666667   
18886                       0                 7.000000   
18887                       0                 8.666667   
18888                       0                 7.000000   
18889                       0                 8.666667   
18890                       0                 7.000000   
18891                       0                 8.666667   
18892                       0                 7.000000   

        Fwd Packet Length Std  ...   min_seg_size_forward  Active Mean  \
18883               10.263203  ...                     20          0.0   
18884                0.000000  ...                     20          0.0   
18885               10.263203  ...                     20          0.0   
18886                5.656854  ...                     20        939.0   
18887               10.263203  ...                     20          0.0   
18888                5.656854  ...                     20        911.0   
18889               10.263203  ...                     20          0.0   
18890                5.656854  ...                     20        877.0   
18891               10.263203  ...                     20          0.0   
18892                5.656854  ...                     20        739.0   

        Active Std   Active Max   Active Min   Idle Mean    Idle Std  \
18883          0.0            0            0         0.0         0.0   
18884          0.0            0            0         0.0         0.0   
18885          0.0            0            0         0.0         0.0   
18886          0.0          939          939  39300000.0  44200000.0   
18887          0.0            0            0         0.0         0.0   
18888          0.0          9

In [21]:
benign_df.head(10)

Destination Port   Flow Duration   Total Fwd Packets  \
0              54865               3                   2   
1              55054             109                   1   
2              55055              52                   1   
3              46236              34                   1   
4              54863               3                   2   
5              54871            1022                   2   
6              54925               4                   2   
7              54925              42                   1   
8               9282               4                   2   
9              55153               4                   2   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        0                           12   
1                        1                            6   
2                        1                            6   
3                        1                            6   
4                        0                           12   
5                        0                           12   
6                        0                           12   
7                        1                            6   
8                        0                           12   
9                        0                           37   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             0                       6   
1                             6                       6   
2                             6                       6   
3                             6                       6   
4                             0                       6   
5                             0                       6   
6                             0                       6   
7                             6                       6   
8                             0                       6   
9                             0                      31   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                      6.0                 0.00000   
1                       6                      6.0                 0.00000   
2                       6                      6.0                 0.00000   
3                       6                      6.0                 0.00000   
4                       6                      6.0                 0.00000   
5                       6                      6.0                 0.00000   
6                       6                      6.0                 0.00000   
7                       6                      6.0                 0.00000   
8                       6                      6.0                 0.00000   
9                       6                     18.5                17.67767   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     20          0.0          0.0            0   
2  ...                     20          0.0          0.0            0   
3  ...                     20          0.0          0.0            0   
4  ...                     20          0.0          0.0            0   
5  ...                     20          0.0          0.0            0   
6  ...                     20          0.0          0.0            0   
7  ...                     20          0.0          0.0            0   
8  ...                     20          0.0          0.0            0   
9  ...                     20          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          

In [22]:
#article's Features
columns_to_keep = [
    ' Destination Port',
    ' Avg Bwd Segment Size',
    ' Bwd Packet Length Mean',
    ' Packet Length Mean',
    ' Bwd Packets/s',
    ' Max Packet Length',
    ' Bwd Packet Length Std',
    'Init_Win_bytes_forward'
]
X = merged_df[columns_to_keep]
y = merged_df[' Label']

In [23]:
X

Destination Port   Avg Bwd Segment Size   Bwd Packet Length Mean  \
0                   54865                    0.0                      0.0   
1                   55054                    6.0                      6.0   
2                   55055                    6.0                      6.0   
3                   46236                    6.0                      6.0   
4                   54863                    0.0                      0.0   
...                   ...                    ...                      ...   
918443                 53                   76.0                     76.0   
918444                 53                  181.0                    181.0   
918445              58030                    6.0                      6.0   
918446                 53                  128.0                    128.0   
918447                 53                  113.0                    113.0   

         Packet Length Mean   Bwd Packets/s   Max Packet Length  \
0                  6.000000        0.000000                   6   
1                  6.000000     9174.311927                   6   
2                  6.000000    19230.769230                   6   
3                  6.000000    29411.764710                   6   
4                  6.000000        0.000000                   6   
...                     ...             ...                 ...   
918443            41.714286       62.082881                  76   
918444            97.600000     6172.839506                 181   
918445            17.000000    12195.121950                  31   
918446            53.333333        1.907241                 128   
918447            65.857143       21.066158                 113   

         Bwd Packet Length Std  Init_Win_bytes_forward  
0                          0.0                      33  
1                          0.0                      29  
2                          0.0                      29  
3                          0.0                      31  
4                          0.0                      32  
...                        ...                     ...  
918443                     0.0                      -1  
918444                     0.0                      -1  
918445                     0.0                    1006  
918446                     0.0                      -1  
918447                     0.0                      -1  

[917117 rows x 8 columns]

In [ ]:
#Split the data into train,test

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

#standardScaler normalization
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
X_test_transformed = scaler.transform(X_test)

rf = RandomForestClassifier(max_depth=100, random_state=45)
rf.fit(X_train_transformed, y_train)
y_predicted = rf.predict(X_test_transformed)


In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Assuming y_predicted and y_test are your predicted and true labels, respectively.
accuracy = accuracy_score(y_test, y_predicted)
precision = precision_score(y_test, y_predicted, pos_label='DDoS')
recall = recall_score(y_test, y_predicted, pos_label='DDoS')
f1 = f1_score(y_test, y_predicted, pos_label='DDoS')
conf_matrix = confusion_matrix(y_test, y_predicted)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.9968215718771808
Precision: 0.9925633492471538
Recall: 0.9997886198195342
F1 Score: 0.9961628833003152
Confusion Matrix:
 [[107164    567]
 [    16  75677]]


In [ ]:
#Split the data into train, val , test

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing


# Split the data into training (80%), validation (10%), and test (10%) sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# StandardScaler normalization
scaler = StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
X_val_transformed = scaler.transform(X_val)
X_test_transformed = scaler.transform(X_test)

# Initialize and train RandomForestClassifier
rf = RandomForestClassifier(max_depth=100, random_state=45)
rf.fit(X_train_transformed, y_train)

# Predict on the validation set
y_val_predicted = rf.predict(X_val_transformed)

# Predict on the test set
y_test_predicted = rf.predict(X_test_transformed)




Confusion Matrix (Validation):
[[53648   259]
 [    7 37798]]
Classification Report (Validation):
              precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     53907
        DDoS       0.99      1.00      1.00     37805

    accuracy                           1.00     91712
   macro avg       1.00      1.00      1.00     91712
weighted avg       1.00      1.00      1.00     91712

Confusion Matrix (Test):
[[53516   308]
 [    9 37879]]
Classification Report (Test):
              precision    recall  f1-score   support

      BENIGN       1.00      0.99      1.00     53824
        DDoS       0.99      1.00      1.00     37888

    accuracy                           1.00     91712
   macro avg       1.00      1.00      1.00     91712
weighted avg       1.00      1.00      1.00     91712



In [ ]:
#Test results

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_test_predicted)
precision = precision_score(y_test, y_test_predicted, pos_label='DDoS')
recall = recall_score(y_test, y_test_predicted, pos_label='DDoS')
f1 = f1_score(y_test, y_test_predicted, pos_label='DDoS')
# Evaluate the model on the test set
conf_matrix_test = confusion_matrix(y_test, y_test_predicted)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("Confusion Matrix:(Test)\n", conf_matrix)

Accuracy: 0.9965435275645499
Precision: 0.9919344279466834
Recall: 0.9997624577702703
F1 Score: 0.9958330594807755
Confusion Matrix:(Test)
 [[107164    567]
 [    16  75677]]


In [ ]:
#Val results

In [28]:
accuracy = accuracy_score(y_val, y_val_predicted)
precision = precision_score(y_val, y_val_predicted, pos_label='DDoS')
recall = recall_score(y_val, y_val_predicted, pos_label='DDoS')
f1 = f1_score(y_val, y_val_predicted, pos_label='DDoS')
# Evaluate the model on the validation set
conf_matrix_val = confusion_matrix(y_val, y_val_predicted)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print('Confusion Matrix (Validation)\n:', conf_matrix)

Accuracy: 0.9970996161898116
Precision: 0.9931944188979689
Recall: 0.99981483930697
F1 Score: 0.9964936331760301
Confusion Matrix (Validation)
: [[107164    567]
 [    16  75677]]
